name: Publication
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v2
      with:
        push: true
        tags: dmtucker/dmtucker.github.io:latest
